// Les sous-titres anglais. La clé, c'est le texte en joual (voir i18n.ts).
export const EN: Record<string, string> = {
  "Un plus gros sac": "A bigger bag",
  "+0,10 $ par tape. Un sac de chips, ça tenait pas grand-chose.": "+$0.10 per tap. A chip bag didn't hold much.",
  "Le vieux bicycle à ton oncle": "Your uncle's old bike",
  "+0,25 $/s. Y grince, mais y roule.": "+$0.25/s. It squeaks, but it rolls.",
  "Ti-Guy te donne un coup de main": "Ti-Guy gives you a hand",
  "+1 $/s. Y travaille pour une liqueur pis un sac de chips.": "+$1/s. He works for a pop and a bag of chips.",
  "Une remorque de bicycle": "A bike trailer",
  "+5 $/s. Tu ramasses le stock de tout le rang.": "+$5/s. You haul the whole road's empties.",
  "Contact au dépanneur": "A contact at the corner store",
  "x1,5 sur tous tes gains. Le proprio te fait un prix.": "x1.5 on all your earnings. The owner cuts you a deal.",
  "Route de circulaires": "Flyer route",
  "+15 $/s. Le Publisac, ça se livre pas tout seul.": "+$15/s. Those flyer bags don't deliver themselves.",
  "Déneigement des entrées": "Driveway snow clearing",
  "+60 $/s. Une pelle sur le bazou pis envoye.": "+$60/s. A plow on the beater and off you go.",
  "Remorquage chez les voisins": "Towing for the neighbours",
  "+250 $/s. Tout le monde reste pogné dans le fossé l'hiver.": "+$250/s. Everybody ends up stuck in the ditch come winter.",
  "Une baie de plus": "One more bay",
  "+400 $/s. Un pont élévateur usagé pis un char de plus à la fois.": "+$400/s. A used lift and one more car at a time.",
  "Engager un vrai mécano": "Hire a real mechanic",
  "x2 sur tous tes gains. Ti-Guy est content, y peut enfin prendre son break.": "x2 on all your earnings. Ti-Guy's happy, he can finally take his break.",
  "Des chars sur le lot": "Cars on the lot",
  "+4 000 $/s. Des bazous retapés, garantie de 30 jours (ou 30 km).": "+$4,000/s. Fixed-up beaters, 30-day warranty (or 30 km).",
  "Une pub à la radio locale": "An ad on local radio",
  "x1,5 sur tous tes gains. « Chez Gagnon pis fils, on vous fait un prix! »": "x1.5 on all your earnings. “Gagnon & Son, we'll make you a deal!”",
  "Un vendeur de chars": "A car salesman",
  "+30 000 $/s. Y parle vite pis y a une moustache.": "+$30,000/s. He talks fast and has a moustache.",
  "Batterie": "Battery",
  "La vieille est à terre depuis 2009.": "The old one's been dead since 2009.",
  "Pneus usagés": "Used tires",
  "Fini les blocs de béton. Ça vient du garage à Ti-Guy.": "No more cinder blocks. They come from Ti-Guy's garage.",
  "Démarreur": "Starter",
  "Clic clic clic... pu de clic.": "Click click click... no more click.",
  "Freins": "Brakes",
  "Mettons que ça serait une bonne idée.": "Let's say it'd be a good idea.",
  "Débosser pis peinturer": "Bodywork and paint",
  "x1,25 sur tes gains. Un char propre, ça donne plus de pourboire.": "x1.25 on your earnings. A clean car gets better tips.",
  "Le garage à Ti-Guy": "Ti-Guy's garage",
  "Un vieux garage sur le bord du rang. Tu répares les chars du monde pis ça rentre tout seul.": "An old garage by the side of the road. You fix people's cars and the money rolls in.",
  "Le concessionnaire": "The dealership",
  "Un lot de chars usagés avec des fanions. Le rêve du bonhomme Gagnon.": "A used car lot with little flags. Old man Gagnon's dream.",
  "Ta mère": "Your mom",
  "Ginette du dépanneur": "Ginette from the corner store",
  "Ti-Guy": "Ti-Guy",
  "Le bonhomme Gagnon": "Old man Gagnon",
  "Réjean du magasin général": "Réjean from the general store",
  "L'agent Lapointe": "Officer Lapointe",
  "Monsieur Tremblay, le voisin": "Mr. Tremblay, the neighbour",
  "Un touriste perdu": "A lost tourist",
  "Ton oncle Gérald": "Your uncle Gérald",
  "Envoye, sors du sous-sol! Va ramasser des canettes dans le rang, ça va te faire prendre l'air.": "Come on, get out of the basement! Go pick up cans along the road, some fresh air'll do you good.",
  "Bon! Tu vois que t'es capable. Tiens, un petit 2 piasses pour ta liqueur.": "There! See, you can do it. Here's two bucks for a pop.",
  "Ramasser 25 canettes": "Pick up 25 cans",
  "Allo mon beau! Rapporte-moi pour 10 $ de canettes, pis je te fais un prix sur tes chips.": "Hi sweetie! Bring me $10 worth of cans and I'll give you a deal on chips.",
  "Ça c'est du stock! Garde le change, mon chou.": "Now that's a haul! Keep the change, hon.",
  "Gagner 10 $ au total": "Earn $10 total",
  "Heille, t'as pas d'allure à marcher de même. Ton oncle a un vieux bicycle dans sa remise, achète-lui.": "Hey, you look ridiculous walking around like that. Your uncle's got an old bike in his shed, buy it off him.",
  "Ah ben là! Y grince, mais tu vas faire le rang deux fois plus vite.": "Well look at that! It squeaks, but you'll cover the road twice as fast.",
  "Acheter le vieux bicycle": "Buy the old bike",
  "Pis si on ramassait ensemble? Pour une liqueur pis un sac de chips, je suis ton homme.": "What if we picked up together? For a pop and a bag of chips, I'm your guy.",
  "Deal! On est une business astheure, mon homme.": "Deal! We're a business now, buddy.",
  "Engager Ti-Guy": "Hire Ti-Guy",
  "Mon vieux char dans la cour, y'é à vendre. 500 piasses pis y'é à toé. Y roule pas, mais c'est un bon char.": "My old car in the yard is for sale. 500 bucks and it's yours. Doesn't run, but it's a good car.",
  "Fais attention, y'a du millage, mais y'a du cœur. Bonne chance avec!": "Careful, it's got miles on it, but it's got heart. Good luck with it!",
  "Acheter le bazou": "Buy the beater",
  "Ton char sur les blocs, ça fait pitié. Mon cousin a des pneus usagés, va voir.": "Your car up on blocks is a sorry sight. My cousin's got used tires, go see him.",
  "Ah, ça a déjà plus l'air d'un char!": "Ah, it already looks more like a car!",
  "Mettre des pneus": "Put tires on",
  "Ton char, y roule-tu? Si oui, viens souper dimanche, ton père veut le voir.": "Does your car run yet? If it does, come for supper Sunday, your dad wants to see it.",
  "Ton père dit que ça sonne comme un tracteur. Il est fier pareil.": "Your dad says it sounds like a tractor. He's proud anyway.",
  "Faire rouler le bazou": "Get the beater running",
  "Le gars des circulaires a lâché. Ça te tente-tu de faire la route avec ton char?": "The flyer guy quit. Want to do the route with your car?",
  "Tout le rang a eu son Publisac. T'es mon sauveur!": "The whole road got its flyers. You're a lifesaver!",
  "Prendre la route de circulaires": "Take the flyer route",
  "Je l'reconnais pu, ton char! Mais la rouille... Débosse-moi ça, ça te ferait honneur.": "I barely recognize your car! But the rust... Fix up that body, you'd be proud of it.",
  "Ben coudonc. Y'é plus beau que quand je l'ai acheté en 1987.": "Well I'll be. It looks better than when I bought it in 1987.",
  "J'ai une idée de fou : on ouvre un garage. Mais faut du cash. Mettons... 2,7 millions de gagné.": "I've got a crazy idea: we open a garage. But we need cash. Let's say... 2.7 million earned.",
  "On a le cash! Astheure, faut juste l'acheter, ce garage-là.": "We've got the cash! Now we just have to buy that garage.",
  "Gagner 2,7 M $ au total": "Earn $2.7M total",
  "Le vieux garage au coin du rang est à vendre. 2,7 millions. On le prend-tu?": "The old garage at the corner is for sale. 2.7 million. Do we take it?",
  "On est ouverts! J'ai déjà accroché le calendrier de pneus.": "We're open! I already hung up the tire calendar.",
  "Acheter le garage": "Buy the garage",
  "Tout le monde au dépanneur parle de ton garage. Ajoute une baie, y'a du monde qui attend!": "Everybody at the store's talking about your garage. Add a bay, people are lining up!",
  "Ma Corolla est réparée en deux jours. Je te fais de la pub, mon chou.": "My little car got fixed in two days. I'll spread the word, hon.",
  "Ajouter une baie": "Add a bay",
  "J'prends ma retraite. Mon terrain sur le bord de la route ferait un beau lot de chars... 200 millions, pis y'é à toé.": "I'm retiring. My land by the highway would make a nice car lot... 200 million and it's yours.",
  "« Chez Gagnon pis fils ». J'ai pas de fils, mais toé, t'es comme.": "“Gagnon & Son.” I don't have a son, but you're close enough.",
  "Acheter le concessionnaire": "Buy the dealership",
  "Mon gars, un empire! Mais t'as l'air fatigué. Vends toute un jour, pis recommence plus grand.": "My boy, an empire! But you look tired. Sell it all someday, and start over bigger.",
  "Je l'ai toujours dit que t'irais loin.": "I always said you'd go far.",
  "Gagner 1 T $ au total": "Earn $1T total",
  "Chips pis liqueur": "Chips and pop",
  "Tapes x1,5 pendant 5 min. Le combo du midi.": "Taps x1.5 for 5 min. The lunch combo.",
  "Café filtre": "Drip coffee",
  "Passif x1,5 pendant 5 min. Ça goûte le brûlé, mais ça réveille la gang.": "Passive x1.5 for 5 min. Tastes burnt, but it wakes the crew up.",
  "Caisse de 24 « La Brune du Rang »": "24-pack of “Back Road Brown”",
  "Tapes x2 pendant 5 min. Ti-Guy livre plus vite avec une frette qui l’attend.": "Taps x2 for 5 min. Ti-Guy delivers faster with a cold one waiting.",
  "Paquet de « Rouges du Rang »": "Pack of “Back Road Reds”",
  "Passif x2 pendant 2 min. Une pause smoke, pis la gang revient en feu.": "Passive x2 for 2 min. A smoke break, and the crew comes back on fire.",
  "Vape saveur barbe à papa": "Cotton candy vape",
  "Tapes x1,5 pendant 15 min. Ça sent la cabane à sucre dans le char.": "Taps x1.5 for 15 min. The car smells like a sugar shack.",
  "Vin de dépanneur": "Corner store wine",
  "Passif x1,5 pendant 15 min. Une bouteille de rouge pas chère pour le souper.": "Passive x1.5 for 15 min. A cheap bottle of red for supper.",
  "Vers de terre": "Earthworms",
  "Passif x1,25 pendant 30 min. Ti-Guy part à la pêche, la gang travaille en paix.": "Passive x1.25 for 30 min. Ti-Guy goes fishing, the crew works in peace.",
  "Corde de bois": "Cord of firewood",
  "Passif x1,25 pendant 1 h. Une maison chaude, une gang heureuse.": "Passive x1.25 for 1 h. A warm house, a happy crew.",
  "Salut mon gars! Y'a de la frette dans le frigidaire pis du café sur le rond.": "Hey bud! There's cold beer in the fridge and coffee on the burner.",
  "Cash seulement, la machine à cartes est encore brisée.": "Cash only, the card machine's broken again.",
  "Ta mère est passée tantôt. A m'a dit que tu travaillais fort, astheure.": "Your mom came by earlier. Says you're working hard these days.",
  "Le vin est en spécial. Ben, y'est toujours en spécial.": "Wine's on special. Well, it's always on special.",
  "Si tu vas à la pêche, prends des vers. Les miens sont frais d'à matin.": "If you're going fishing, grab some worms. Mine are fresh this morning.",
  "Le pouce qui chauffe": "Hot thumb",
  "Taper 100 fois.": "Tap 100 times.",
  "Tendinite du rang": "Back road tendinitis",
  "Taper 1 000 fois.": "Tap 1,000 times.",
  "Pas d'autre chose à faire": "Nothing better to do",
  "Taper 10 000 fois.": "Tap 10,000 times.",
  "Un beau mille": "A cool grand",
  "Gagner 1 000 $ au total.": "Earn $1,000 total.",
  "Le gros lot du dépanneur": "Corner store jackpot",
  "Gagner 100 000 $ au total.": "Earn $100,000 total.",
  "Millionnaire du rang": "Back road millionaire",
  "Gagner 10 M $ au total.": "Earn $10M total.",
  "Plus riche que le maire": "Richer than the mayor",
  "Gagner 1 G $ au total.": "Earn $1B total.",
  "Propriétaire": "Owner",
  "Acheter le bazou du bonhomme Gagnon.": "Buy old man Gagnon's beater.",
  "Vroum vroum": "Vroom vroom",
  "Faire rouler le bazou.": "Get the beater running.",
  "Beau comme un char neuf": "Good as new",
  "Débosser pis peinturer le bazou.": "Do the beater's bodywork and paint.",
  "En affaires": "In business",
  "Acheter le garage à Ti-Guy.": "Buy Ti-Guy's garage.",
  "Le rêve à Gagnon": "Gagnon's dream",
  "Acheter le concessionnaire.": "Buy the dealership.",
  "Bon garçon": "Good boy",
  "Finir toutes les quêtes.": "Finish every quest.",
  "Ça commence à rouler": "Getting rolling",
  "Monter un achat au niveau 10.": "Get an upgrade to level 10.",
  "Au boutte": "Maxed out",
  "Monter un achat au max.": "Max out an upgrade.",
  "Double ou rien": "Double or nothing",
  "Partir un boost x2.": "Start an x2 boost.",
  "Accro au boost": "Boost addict",
  "Partir 10 boosts x2.": "Start 10 x2 boosts.",
  "Client régulier": "Regular customer",
  "Acheter 10 affaires chez Réjean.": "Buy 10 things at Réjean's.",
  "Une bonne heure": "A good hour",
  "Jouer une heure au total.": "Play for an hour total.",
  "Patenteux": "Tinkerer",
  "Retaper un char au complet.": "Fully restore a car.",
  "Collectionneur": "Collector",
  "Retaper tous les chars.": "Restore every car.",
  "Toujours de quoi dans le rang": "Always something on the road",
  "Répondre à 10 événements.": "Answer 10 events.",
  "On recommence": "Starting over",
  "Vendre l'empire une première fois.": "Sell the empire for the first time.",
  "PRINTEMPS": "SPRING",
  "Le dégel pis les nids-de-poule : baies du garage x2, remorquage x1,5. L'eau d'érable coule : chaudières x2.": "Thaw and potholes: garage bays x2, towing x1.5. The sap is running: sap buckets x2.",
  "ÉTÉ": "SUMMER",
  "Les touristes laissent traîner des canettes : tapes x1,5. Bicycle x2, les chars usagés partent vite (lot x1,5), pis la terrasse du bar est pleine (chansonnier x1,5).": "Tourists leave cans everywhere: taps x1.5. Bike x2, used cars sell fast (lot x1.5), and the bar patio is packed (folk singer x1.5).",
  "AUTOMNE": "FALL",
  "Ti-Guy revient de la chasse en forme : Ti-Guy x2. Les circulaires de l'Halloween x2.": "Ti-Guy's back from hunting and fired up: Ti-Guy x2. Halloween flyers x2.",
  "HIVER": "WINTER",
  "Déneigement x3, remorquage x2 pis la glace de l'aréna x2. Le bicycle dans la neige, par exemple... x0,5.": "Snow clearing x3, towing x2 and arena ice x2. The bike in the snow, though... x0.5.",
  "Le pick-up rouillé à Ti-Guy": "Ti-Guy's rusty pickup",
  "Un Bœuf 1979. Y'a plus de rouille que de tôle, mais la boîte est encore bonne.": "A 1979 Bœuf. More rust than metal, but the box is still good.",
  "Moteur": "Engine",
  "Fond de boîte": "Truck bed floor",
  "Pare-brise": "Windshield",
  "La Grand Monarque à matante Huguette": "Aunt Huguette's Grand Monarque",
  "Un salon sur quatre roues. Les bancs de velours sont pognés dans le plastique depuis 1991.": "A living room on four wheels. The velvet seats have been wrapped in plastic since 1991.",
  "Transmission": "Transmission",
  "Suspension": "Suspension",
  "Toit de vinyle": "Vinyl roof",
  "Le Bolide 1970": "The 1970 Bolide",
  "Un vrai char de muscle, trouvé sous une bâche dans une grange à Saint-Clin-Clin.": "A real muscle car, found under a tarp in a barn in Saint-Clin-Clin.",
  "Le V8": "The V8",
  "Les chromes": "The chrome",
  "Des flammes sur le capot": "Flames on the hood",
  "Mon ami, ton silencieux est percé. Ça s'entend jusqu'au village.": "Buddy, your muffler's got a hole in it. They can hear you all the way to the village.",
  "Payer l'amende": "Pay the fine",
  "Jaser de hockey": "Talk hockey",
  "Vente de garage! Une boîte de vieilleries, je te la laisse pour pas cher.": "Garage sale! A box of old junk, I'll let it go cheap.",
  "Acheter la boîte": "Buy the box",
  "Non merci": "No thanks",
  "Excuse me... le chemin du chalet, c'est par où?": "Excusez-moi... which way to the cottage?",
  "L'aider": "Help him",
  "Le niaiser": "Mess with him",
  "Bingo au sous-sol de l'église à soir! La carte est pas chère.": "Bingo in the church basement tonight! Cards are cheap.",
  "Jouer": "Play",
  "Pas à soir": "Not tonight",
  "J'ai besoin d'un coup de main à la cabane à sucre. Je paye en cash pis en tire.": "I need a hand at the sugar shack. I pay in cash and maple taffy.",
  "Y aller": "Go",
  "Festival de la gibelotte au village! Y a des canettes vides partout.": "Fish stew festival in the village! There are empty cans everywhere.",
  "Ramasser": "Pick up",
  "J'ai vu un chevreuil dans ton champ! On y va-tu?": "I saw a deer in your field! Should we go?",
  "Rester en dedans": "Stay inside",
  "Tempête de verglas! Tout le rang est dans le fossé.": "Ice storm! The whole road is in the ditch.",
  "Sortir la chaîne": "Get the chain out",
  "OUI": "ON",
  "NON": "OFF",
  "COURTS": "SHORT",
  "COMPLETS": "FULL",
  "JOUAL": "JOUAL",
  "ENGLISH": "ENGLISH",
  "3,99 $": "$3.99",
  "Colle ton code de sauvegarde ici.": "Paste your save code here.",
  "Ce code-là marche pas. Vérifie que t'as tout copié.": "That code doesn't work. Check that you copied all of it.",
  "Remplacer ta partie par celle du code?": "Replace your game with the one in the code?",
  "Partie chargée!": "Game loaded!",
  "Pendant que t'étais parti ({temps}), ta gang a ramassé {cash}.": "While you were gone ({temps}), your crew made {cash}.",
  "Vroum! Ton bazou part du premier coup (ou presque). T'es maintenant livreur de pizza, pis les jobs motorisées sont débloquées.": "Vroom! Your beater starts on the first try (almost). You're a pizza delivery guy now, and driving jobs are unlocked.",
  "« Pas de pubs » ({prix}) va s'acheter dans l'app Android, via Google Play. Sur le web, y'a juste des pubs de démo.": "“No ads” ({prix}) will be sold in the Android app, through Google Play. On the web, there are only demo ads.",
  "Merci! Le boost est gratuit pour toujours, pis y aura pu jamais de pubs.": "Thanks! The boost is free forever, and there'll never be ads again.",
  "Ti-Guy : « On est en affaires! » Le garage est à toé. De nouveaux achats sont débloqués.": "Ti-Guy: “We're in business!” The garage is yours. New upgrades are unlocked.",
  "Le bonhomme Gagnon : « Prends soin de mon lot. » Le concessionnaire est à toé, pis la radio locale t'attend.": "Old man Gagnon: “Take care of my lot.” The dealership is yours, and local radio is waiting for you.",
  "Vendre l'empire? Tu repars à pied avec 0 $, mais tu gagnes {points} points de réputation (+{pc} % sur tous tes gains, pour toujours).": "Sell the empire? You start over on foot with $0, but you earn {points} reputation points (+{pc}% on all your earnings, forever).",
  "Le rang au complet parle de toé. +{points} points de réputation. Envoye, on recommence, mais plus vite cette fois-citte.": "The whole road is talking about you. +{points} reputation points. Come on, let's start over, but faster this time.",
  "Le bonhomme Gagnon : « Y'é à toé, mon gars. Y roule pas, y'a pu de batterie pis y'é sur les blocs, mais c'est un bon char. »": "Old man Gagnon: “It's yours, kid. Doesn't run, no battery and it's up on blocks, but it's a good car.”",
  "Tout effacer pis recommencer à zéro? Tout part : réputation, succès, stats pis « pas de pubs ».": "Erase everything and start from scratch? It all goes: reputation, achievements, stats and “no ads”.",
  "SUCCÈS": "AWARDS",
  "SUCCÈS : {nom} (+{pc} %)": "ACHIEVEMENT: {nom} (+{pc}%)",
  "{n} / {total} : +{pc} % sur tous tes gains": "{n} / {total}: +{pc}% on all your earnings",
  "Passer le tuto": "Skip tutorial",
  "RÉPARÉ": "FIXED",
  "NIV.": "LVL",
  "AU MAX": "MAXED",
  "RÉPUTATION": "REPUTATION",
  "Tu repars à zéro avec {points} points de réputation (+{pc} % pour toujours).": "You start over with {points} reputation points (+{pc}% forever).",
  "Disponible à {min} gagnés au total. T'es rendu à {cash}.": "Available at {min} earned total. You're at {cash}.",
  "Boost x2": "x2 boost",
  "Tes tapes pis ton passif x2.": "Your taps and idle income x2.",
  "Il reste {temps}.": "{temps} left.",
  "Une fois retapé : {x} sur tous tes gains.": "Once restored: {x} on all your earnings.",
  "{nom} est retapé! Il reste dans ta cour : {x} sur tous tes gains.": "{nom} is restored! It stays in your yard: {x} on all your earnings.",
  "RETAPÉ": "RESTORED",
  "À TOÉ": "YOURS",
  "Tape ici pour ramasser des canettes. Chaque canette consignée, c’est 10 cennes!": "Tap here to pick up cans. Each returnable can is worth 10 cents!",
  "T’as 1 $! Achète un plus gros sac : chaque tape va rapporter plus.": "You've got $1! Buy a bigger bag: every tap will earn more.",
  "Ta mère a une job pour toé. Quand la barre est pleine, réclame ta récompense.": "Your mom has a job for you. When the bar is full, claim your reward.",
  "Dans le MENU : tes succès, tes stats pis les options. Bonne game!": "In the MENU: your achievements, stats and options. Have fun!",
  "Tu paies {x}. L'agent te souhaite une bonne journée.": "You pay {x}. The officer wishes you a good day.",
  "Y'é fan de la même équipe que toé. Y te laisse partir avec un clin d'œil.": "He cheers for the same team as you. He lets you go with a wink.",
  "Mauvaise équipe. Amende double : {x}.": "Wrong team. Double fine: {x}.",
  "Y'avait une vieille carte de hockey de collection dedans! Tu la revends {x}.": "There was a vintage hockey card inside! You sell it for {x}.",
  "Des vieux catalogues pis une lampe à l'huile. Ça valait {x}, mettons.": "Old catalogues and an oil lamp. Worth {x}, I guess.",
  "Tu continues ton chemin.": "You keep on driving.",
  "Y te donne {x} de pourboire. « Thank you! »": "He tips you {x}. “Merci!”",
  "Tu l'envoies dans le rang d'en face. Pas de pourboire, mais t'as ri.": "You send him down the wrong road. No tip, but you had a laugh.",
  "BINGO! Tu gagnes {x}.": "BINGO! You win {x}.",
  "Pas chanceux. La carte t'a coûté {x}.": "No luck. The card cost you {x}.",
  "Ginette : « Une autre fois, mon chou. »": "Ginette: “Another time, hon.”",
  "Tu fais bouillir toute la journée. Ton oncle te donne {x}.": "You boil sap all day. Your uncle gives you {x}.",
  "Trois sacs de canettes. Ça fait {x}.": "Three bags of cans. That's {x}.",
  "Ti-Guy le rate, mais un chasseur de la ville vous paye {x} pour la place.": "Ti-Guy misses it, but a city hunter pays you {x} for the spot.",
  "Vous voyez rien pantoute. Une belle journée dans le bois pareil.": "You see nothing at all. A nice day in the woods anyway.",
  "Ti-Guy : « Pas grave, je vais y aller avec mon beau-frère. »": "Ti-Guy: “No biggie, I'll go with my brother-in-law.”",
  "Tu sors six chars du fossé. Ça fait {x}.": "You pull six cars out of the ditch. That's {x}.",
  "MERCI!": "THANKS!",
  "MAISON": "HOME",
  "MAGASIN": "STORE",
  "GARAGE": "GARAGE",
  "LOT": "LOT",
  "RÉJEAN DU MAGASIN GÉNÉRAL": "RÉJEAN FROM THE GENERAL STORE",
  "[ RÉCLAMER ]": "[ CLAIM ]",
  "PROCHAIN : TON PREMIER BAZOU": "NEXT: YOUR FIRST BEATER",
  "[ ACHETER LE BAZOU ]": "[ BUY THE BEATER ]",
  "TON BAZOU": "YOUR BEATER",
  "TON EMPIRE": "YOUR EMPIRE",
  "Vendre l'empire": "Sell the empire",
  "VENDRE": "SELL",
  "CHARS À RETAPER": "CARS TO RESTORE",
  "ACHATS": "UPGRADES",
  "BOUTIQUE": "SHOP",
  "Pas de pubs": "No ads",
  "Le boost x2 devient gratuit, sans pub. Pour toujours, même après le prestige.": "The x2 boost becomes free, no ads. Forever, even after prestige.",
  "STATS": "STATS",
  "OPTIONS": "OPTIONS",
  "Son": "Sound",
  "Lignes VHS": "VHS lines",
  "Langue": "Language",
  "Chiffres": "Numbers",
  "Sauvegarde": "Save",
  "COPIER": "COPY",
  "COLLER": "PASTE",
  "[ CHARGER CE CODE ]": "[ LOAD THIS CODE ]",
  "Recommencer à zéro": "Start from scratch",
  "[ FERMER ]": "[ CLOSE ]",
  "[ NON ]": "[ NO ]",
  "[ OUI ]": "[ YES ]",
  "[ ENVOYE DONC ]": "[ ALRIGHT ]",
  "PUB DE DÉMO": "DEMO AD",
  "Ici, une vraie pub va jouer dans l'app Android. Pour l'instant, on fait semblant.": "A real ad will play here in the Android app. For now, we're pretending.",
  "Menu : succès, stats pis options": "Menu: achievements, stats and options",
  "Ton rang": "Your road",
  "Endroits du rang": "Places on the road",
  "Quantité par achat": "Amount per purchase",
  "Menu": "Menu",
  "Code de sauvegarde": "Save code",
  "Code copié! Garde-le en lieu sûr.": "Code copied! Keep it somewhere safe.",
  "Copie ce code pis garde-le en lieu sûr.": "Copy this code and keep it somewhere safe.",
  "Temps joué": "Time played",
  "Gagné cette partie": "Earned this run",
  "Gagné à vie": "Earned all-time",
  "Revenu": "Income",
  "Une tape": "One tap",
  "Tapes cette partie": "Taps this run",
  "Tapes à vie": "Taps all-time",
  "Boosts x2": "x2 boosts",
  "Achats chez Réjean": "Buys at Réjean's",
  "Événements": "Events",
  "Quêtes finies": "Quests done",
  "Empires vendus": "Empires sold",
  "Réputation": "Reputation",
  "Succès": "Achievements",
  "LIVRER DES PIZZAS": "DELIVERING PIZZAS",
  "RAMASSER DES CANETTES": "PICKING UP CANS",
  "[ LIVRER ]": "[ DELIVER ]",
  "[ RAMASSER ]": "[ PICK UP ]",
  "ÇA ROULE!": "IT RUNS!",
  "SUR LES BLOCS": "ON BLOCKS",
  "[ BOOST x2 ]": "[ BOOST x2 ]",
  "[ PUB : BOOST x2 ]": "[ AD: BOOST x2 ]",
  "10 MIN GRATUITES": "10 FREE MIN",
  "10 MIN POUR UNE PUB": "10 MIN FOR AN AD",
  "ACHETÉ": "BOUGHT",
  "[ CHERCHER MON BOOST ]": "[ GET MY BOOST ]",
  // La radio du char
  "RADIO RANG 98,7": "BACKROAD RADIO 98.7",
  "GARAGE FM 103,3": "GARAGE FM 103.3",
  "Vous écoutez Radio Rang, 98,7. La radio qui sent le diesel pis la tarte au sucre.": "You're listening to Backroad Radio, 98.7. The station that smells like diesel and sugar pie.",
  "Garage FM, 103,3. Du rock sale pour du monde propre. Ou l’inverse.": "Garage FM, 103.3. Dirty rock for clean folks. Or the other way around.",
  "Le reel du bazou": "The Beater Reel",
  "Ma blonde est partie avec ma motoneige": "My Girl Left With My Snowmobile",
  "Le blues du dépanneur": "Corner Store Blues",
  "Mononc' a vendu la terre": "Uncle Sold the Farm",
  "Silencieux percé": "Busted Muffler",
  "Pédale dans l'tapis": "Pedal to the Floor",
  "Ma minoune rouille en paix": "My Old Junker Rusts in Peace",
  "Brake à bras": "Handbrake",
  "Pneus Bouchard, sur la 132! Achetez-en trois, le quatrième est usagé. Pneus Bouchard : on roule, nous autres.": "Bouchard Tires, on Route 132! Buy three, the fourth one's used. Bouchard Tires: we keep on rolling.",
  "Casse-croûte Chez Lulu, à 5 km passé l’église. La poutine qui te colle au corps jusqu’au printemps. Cash seulement, le terminal marche pas.": "Lulu's snack bar, 5 km past the church. Poutine that sticks to your ribs till spring. Cash only, the card machine's busted.",
  "Le bingo de la Fabrique, mardi soir à 7 h. 2 $ la carte, café compris. Apportez vos bouchons pis votre chance.": "Parish bingo, Tuesday night at 7. $2 a card, coffee included. Bring your bottle caps and your luck.",
  "Garage Ti-Guy : on répare toute, même ce qui marchait. Pas besoin de rendez-vous, klaxonnez dans la cour.": "Ti-Guy's Garage: we fix everything, even what was working. No appointment needed, just honk in the yard.",
  "La météo du rang : y fait frette à matin, pis plus frette à soir. Mettez une tuque pis partez le char d’avance.": "Backroad weather: freezing this morning, colder tonight. Wear a toque and warm up the car ahead of time.",
  "Grosse vente de garage chez le bonhomme Gagnon samedi! Des roues, de la tôle pis un frigo qui marche quasiment. Prix négociables.": "Big garage sale at old man Gagnon's on Saturday! Wheels, sheet metal and a fridge that almost works. Prices negotiable.",
  "Érablière Chez Ti-Paul : le temps des sucres est commencé! Tire sur la neige, oreilles de crisse pis danse en ligne à 2 h.": "Ti-Paul's Sugar Shack: sugaring season is on! Maple taffy on snow, fried pork rinds and line dancing at 2.",
  "Club de motoneige du rang : 40 km de sentiers ouverts. Restez dans les piquets, le bonhomme Gagnon surveille ses clôtures.": "Backroad Snowmobile Club: 40 km of trails open. Stay between the stakes, old man Gagnon is watching his fences.",
  "PUB": "AD",
  "RADIO FERMÉE": "RADIO OFF",
  "FERMÉE": "OFF",
  "Radio": "Radio",
  "Volume radio": "Radio volume",
  "Effets sonores": "Sound effects",
  "Radio : {texte}. Change de poste.": "Radio: {texte}. Tap for the next station.",
  // Les nouveaux endroits : cabane à sucre, bar, aréna
  "Des chaudières d'eau d'érable": "Maple sap buckets",
  "+1 500 $/s. Ton oncle Gérald fait bouillir, toi tu ramasses.": "+$1,500/s. Uncle Gérald boils, you collect.",
  "La tire sur la neige": "Maple taffy on snow",
  "x1,5 sur tous tes gains. Les touristes font la file jusque dans le rang.": "x1.5 on all earnings. Tourists line up all the way down the road.",
  "Le chansonnier du vendredi": "Friday night folk singer",
  "+12 000 $/s. Y connaît juste trois tounes, mais y les fait ben.": "+$12,000/s. He only knows three songs, but he plays them well.",
  "La soirée karaoké": "Karaoke night",
  "x1,5 sur tous tes gains. Ginette chante la même toune depuis 1998.": "x1.5 on all earnings. Ginette has sung the same song since 1998.",
  "Louer la glace": "Rent out the ice",
  "+60 000 $/s. Les ligues de garage jouent jusqu'à minuit.": "+$60,000/s. Beer leagues play until midnight.",
  "Le tournoi de hockey bottine": "The ball hockey tournament",
  "x1,5 sur tous tes gains. Tout le comté vient voir la finale.": "x1.5 on all earnings. The whole county comes to watch the final.",
  "La cabane à sucre": "The sugar shack",
  "La vieille cabane à ton oncle Gérald, dans le bois en arrière. Y manque juste quelqu'un pour la partir.": "Uncle Gérald's old shack in the back woods. It just needs someone to fire it up.",
  "Le bar du village": "The village bar",
  "Le Bar chez Rollande, avec sa table de pool pis son juke-box. Rollande veut prendre sa retraite.": "Rollande's Bar, with its pool table and jukebox. Rollande wants to retire.",
  "L'aréna": "The arena",
  "L'aréna du village, avec sa Zamboni de 1974 pis ses estrades en bois. Le conseil municipal la vend.": "The village arena, with its 1974 Zamboni and wooden bleachers. Town council is selling it.",
  "Ton oncle Gérald : « Enfin! On va faire du sirop comme dans le temps. » La cabane à sucre est à toé.": "Uncle Gérald: “Finally! We'll make syrup like the old days.” The sugar shack is yours.",
  "Rollande : « Prends soin de mes habitués. » Le bar du village est à toé.": "Rollande: “Take care of my regulars.” The village bar is yours.",
  "Le maire : « Le hockey du samedi est sauvé! » L'aréna est à toé.": "The mayor: “Saturday hockey is saved!” The arena is yours.",
  "Rollande du bar": "Rollande from the bar",
  "Le maire Bouchard": "Mayor Bouchard",
  "Ma vieille cabane à sucre dort dans le bois depuis dix ans. 20 millions pis a l'est à toé, mais faut la faire bouillir!": "My old sugar shack has been sleeping in the woods for ten years. 20 million and it's yours, but you gotta keep it boiling!",
  "Sens-tu ça? C'est l'odeur du printemps, mon neveu.": "Smell that? That's the smell of spring, kid.",
  "Acheter la cabane à sucre": "Buy the sugar shack",
  "Trente ans que je sers des draffes au village. Mon bar est à vendre, 4 milliards, mais tu gardes la table de pool!": "Thirty years pouring drafts in this village. My bar's for sale, 4 billion, but you keep the pool table!",
  "Les habitués t'ont adopté. Ça veut dire qu'y vont te demander du crédit.": "The regulars adopted you. That means they'll ask you for credit.",
  "Acheter le bar du village": "Buy the village bar",
  "La ville peut pu payer l'aréna. 25 milliards pis le hockey du samedi est sauvé. Le village compte sur toé!": "The town can't afford the arena anymore. 25 billion and Saturday hockey is saved. The village is counting on you!",
  "Le conseil va te nommer citoyen de l'année. Y'a même pas eu de vote.": "Council's naming you citizen of the year. There wasn't even a vote.",
  "Acheter l'aréna": "Buy the arena",
  "Sucrier": "Sugar maker",
  "Acheter la cabane à sucre.": "Buy the sugar shack.",
  "Pilier de taverne": "Bar regular",
  "Acheter le bar du village.": "Buy the village bar.",
  "Citoyen de l'année": "Citizen of the year",
  "Acheter l'aréna.": "Buy the arena.",
  "CABANE": "SHACK",
  "BAR": "BAR",
  "ARÉNA": "ARENA",
  // Les fêtes québécoises
  "TEMPS DES SUCRES": "SUGARING SEASON",
  "Tout le village monte à la cabane : tire sur la neige, oreilles de crisse pis set carré.": "The whole village heads to the sugar shack: maple taffy, fried pork rinds and square dancing.",
  "SAINT-JEAN": "SAINT-JEAN",
  "Feu de joie, drapeaux pis Gens du pays à tue-tête.": "Bonfire, flags and Gens du pays at the top of everyone's lungs.",
  "HALLOWEEN": "HALLOWEEN",
  "Des citrouilles sur toutes les galeries pis des bonbons plein les poches.": "Pumpkins on every porch and pockets full of candy.",
  "PARTY DE NOËL": "CHRISTMAS PARTY",
  "Les lumières sont posées, la tourtière est chaude pis mononc est déjà paqueté.": "The lights are up, the tourtière is hot and uncle is already hammered.",
  "Fêtard": "Party animal",
  "Fêter les quatre fêtes du rang.": "Celebrate all four holidays on the road.",
  "C'est le temps des sucres! Viens manger à la cabane, y'a du jambon pis de la tire pour tout le monde.": "It's sugaring season! Come eat at the shack, there's ham and maple taffy for everyone.",
  "Aller se sucrer le bec": "Go get a sugar fix",
  "Rester travailler": "Keep working",
  "Bonne Saint-Jean! On fait un feu de joie dans le champ. Tu fournis la bière?": "Happy Saint-Jean! We're lighting a bonfire in the field. You bringing the beer?",
  "Fournir la bière": "Bring the beer",
  "Juste regarder le feu": "Just watch the fire",
  "Les enfants passent l'Halloween dans le rang à soir. T'as-tu des bonbons?": "Kids are trick-or-treating down the road tonight. Got any candy?",
  "Donner des chips": "Hand out chips",
  "Éteindre les lumières": "Turn off the lights",
  "Le party de Noël est chez nous cette année. Tu fais l'échange de cadeaux?": "The Christmas party's at our place this year. You doing the gift exchange?",
  "Faire l'échange": "Do the exchange",
  "Manger de la tourtière": "Eat tourtière",
  "Tu vends du sirop aux visiteurs entre deux oreilles de crisse. Ça fait {x}.": "You sell syrup to visitors between two plates of pork rinds. That's {x}.",
  "Ton oncle : « Je te garde un pot de sirop. »": "Your uncle: “I'll save you a jar of syrup.”",
  "Le monde est content, pis tout le village passe acheter chez vous. Tu fais {x}.": "Everyone's happy, and the whole village comes to buy from you. You make {x}.",
  "Gens du pays jusqu'à trois heures du matin. La bière t'a coûté {x}, mais quelle soirée.": "Gens du pays until three in the morning. The beer cost you {x}, but what a night.",
  "Monsieur Tremblay : « La prochaine fois! »": "Mr. Tremblay: “Next time!”",
  "Les parents sont contents pis reviennent au dépanneur. Ça te rapporte {x}.": "The parents are happy and come back to the corner store. That earns you {x}.",
  "Le lendemain, ta boîte aux lettres est pleine de papier de toilette.": "Next morning, your mailbox is full of toilet paper.",
  "Tu pioches le billet de loto de mononc. Y'é gagnant : {x}!": "You draw uncle's lottery ticket. It's a winner: {x}!",
  "Tu pioches des bas de laine. Ton cadeau à toé a coûté {x}.": "You draw wool socks. Your own gift cost {x}.",
  "Trois pointes de tourtière plus tard, tu fais une sieste sur le divan.": "Three slices of tourtière later, you nap on the couch.",
  "Chaque saison dure 10 minutes, pis finit avec une fête.": "Each season lasts 10 minutes and ends with a holiday.",
  "Gains {x}.": "Earnings {x}.",
  "C'est la vraie date : la fête dure toute la journée!": "It's the real date: the party lasts all day!",
  "La fête dure 3 minutes.": "The party lasts 3 minutes.",
  // Le look du bazou pis les mini-jeux
  "Peinture": "Paint job",
  "Brun d'origine": "Factory brown",
  "Rouge pompier": "Fire-engine red",
  "Bleu poudre": "Powder blue",
  "Vert forêt": "Forest green",
  "Jaune moutarde": "Mustard yellow",
  "Noir mat": "Matte black",
  "Collants": "Decals",
  "Aucun collant": "No decals",
  "Numéro de course": "Race number",
  "Bandes de course": "Racing stripes",
  "Flammes sur le capot": "Flames on the hood",
  "Mags": "Rims",
  "Roues d'acier": "Steel wheels",
  "Mags chromés": "Chrome rims",
  "Mags rouges": "Red rims",
  "Mags dorés": "Gold rims",
  "Flaps de bouette": "Mud flaps",
  "Pas de flaps": "No mud flaps",
  "Flaps noirs": "Black mud flaps",
  "Flaps rouges": "Red mud flaps",
  "Flaps chromés": "Chrome mud flaps",
  "Réparer le moteur": "Fix the engine",
  "Tape quand l'aiguille est dans le vert. Trois coups de clé.": "Tap when the needle is in the green. Three turns of the wrench.",
  "Déneiger l'entrée": "Shovel the driveway",
  "Passe ton doigt sur la neige avant que le temps finisse. L'hiver seulement.": "Swipe over the snow before time runs out. Winter only.",
  "Prends le bazou en premier.": "Get the beater first.",
  "Y'a pas de neige. Reviens l'hiver.": "No snow right now. Come back in winter.",
  "Mini-jeux joués": "Mini-games played",
  "Tape quand l'aiguille est dans le vert.": "Tap when the needle is in the green.",
  "COUP DE CLÉ {n}/{total}": "WRENCH TURN {n}/{total}",
  "VROUM!": "VROOM!",
  "CLONK!": "CLUNK!",
  "Passe ton doigt sur la neige pour pelleter.": "Swipe over the snow to shovel it.",
  "Du travail de pro! +{cash}": "Pro work! +{cash}",
  "Pas pire pantoute. +{cash}": "Not bad at all. +{cash}",
  "Ouin... Tu feras mieux la prochaine fois. +{cash}": "Yeah... You'll do better next time. +{cash}",
  "JOUER": "PLAY",
  "jusqu'à {cash}": "up to {cash}",
  "{nom} (aperçu)": "{nom} (preview)",
  "POSÉ": "ON",
  "POSER": "PUT ON",
  "LE LOOK DU BAZOU": "PIMP THE BEATER",
  "MINI-JEUX": "MINI-GAMES",
  "[ LÂCHER ]": "[ QUIT ]",
  // L'atelier à Ti-Guy
  "Sur le toit": "On the roof",
  "Rien sur le toit": "Nothing on the roof",
  "Galerie de toit": "Roof rack",
  "Matelas du 1er juillet": "Moving Day mattress",
  "Canot de chalet": "Cottage canoe",
  "Sapin de Noël attaché": "Christmas tree tied on top",
  "Antenne": "Antenna",
  "Pas d'antenne": "No antenna",
  "Antenne de CB": "CB antenna",
  "Drapeau fleurdelisé": "Quebec flag",
  "Queue de raton laveur": "Raccoon tail",
  "ACHETER {prix}": "BUY {prix}",
  "Peinture, mags, toit pis plus. {n} / {total} pièces dans ta collection.": "Paint, rims, roof and more. {n} / {total} pieces in your collection.",
  "[ ALLER À L'ATELIER ]": "[ GO TO THE SHOP ]",
  "L'ATELIER À TI-GUY": "TI-GUY'S SHOP",
  "Ton bazou. Glisse le doigt pour le virer de bord.": "Your beater. Swipe to spin it around.",
  "Catégories": "Categories",
  "Swimming dans le trafic": "Swimming in traffic",
  "POUET POUET!": "HONK HONK!",
  // L'expo de chars
  "Char de course": "Race car",
  "Moé, j'veux voir un char qui a l'air d'aller vite, même stationné.": "I wanna see a car that looks fast even when it's parked.",
  "Un collant de course": "A racing decal",
  "Des mags": "Rims",
  "Rouge ou noir": "Red or black",
  "Prêt pour le chalet": "Cottage ready",
  "Un vrai char de fin de semaine au lac. Faut que ça passe dans le chemin de terre.": "A real weekend-at-the-lake car. It's gotta make it down the dirt road.",
  "Un canot ou une galerie": "A canoe or a roof rack",
  "Des flaps de bouette": "Mud flaps",
  "Vert ou brun": "Green or brown",
  "Fierté du rang": "Backroad pride",
  "Pour la parade du village, je veux du bleu pis du drapeau!": "For the village parade, I want blue and flags!",
  "Le drapeau fleurdelisé": "The Quebec flag",
  "Des bandes de course": "Racing stripes",
  "Le 1er juillet": "Moving Day",
  "Mon gars, montre-moé le char le plus prêt à déménager du comté.": "Son, show me the most move-ready car in the county.",
  "Un matelas sur le toit": "A mattress on the roof",
  "Une antenne de CB ou une queue de raton": "A CB antenna or a raccoon tail",
  "Le gros luxe": "Big luxury",
  "Ça brille-tu, ton affaire? Au lot, on vendait juste du beau.": "Does your thing shine? At the lot, we only sold the good stuff.",
  "Des mags dorés ou chromés": "Gold or chrome rims",
  "Des flaps chromés": "Chrome mud flaps",
  "Noir mat ou jaune moutarde": "Matte black or mustard yellow",
  "Le temps des fêtes": "Holiday season",
  "Un char qui sent le réveillon, c'est ça que je veux voir.": "A car that smells like Christmas Eve dinner, that's what I wanna see.",
  "Un sapin sur le toit": "A tree on the roof",
  "Rouge ou vert": "Red or green",
  "Des mags dorés": "Gold rims",
  "EXPO": "CAR SHOW",
  "1re place! Le juge te donne un trophée pis {cash}.": "1st place! The judge gives you a trophy and {cash}.",
  "2e place. Pas pire pantoute! +{cash}": "2nd place. Not bad at all! +{cash}",
  "Mention honorable. +{cash}": "Honourable mention. +{cash}",
  "Le juge a même pas levé les yeux. Essaie de fitter le thème à la prochaine expo.": "The judge didn't even look up. Try to fit the theme at the next show.",
  "{nom}, JUGE": "{nom}, JUDGE",
  "Thème : {nom}": "Theme: {nom}",
  "Prix : jusqu'à {cash}. Trophées : {n}. Prochaine expo dans {temps}.": "Prize: up to {cash}. Trophies: {n}. Next show in {temps}.",
  "Ton look fitte {n} / {total}": "Your look fits {n} / {total}",
  "INSCRIT": "ENTERED",
  "S'INSCRIRE": "ENTER",
  "La trend du moment : zigzague avec le bazou entre les chars, de plus en plus vite. Frôler un char sans l'accrocher donne du bonus.": "The latest trend: weave the beater between cars, faster and faster. Near misses earn a bonus.",
  "Tape à gauche ou à droite pour zigzaguer entre les chars. Frôle-les sans les accrocher!": "Tap left or right to weave between cars. Get close without hitting them!",
  "FRÔLÉ!": "CLOSE ONE!",
  "Le bazou doit rouler.": "The beater has to run.",
  "DEV": "DEV",
  "Cash": "Cash",
  "x10": "x10",
  "Saison": "Season",
  "SUIVANTE": "NEXT",
  "Fête": "Party",
  "ASTEURE": "NOW",
  "Avancer le temps": "Skip time",
  "+1 H": "+1 H",
  "Heure du jeu": "Game clock",
  "NORMALE": "RESET",
  "Événement": "Event",
  "Mini-jeux": "Mini-games",
  "PRÊTS": "READY",
  "Tuto": "Tutorial",
  "SAUTER": "SKIP",
};
